# -*- coding: utf-8 -*-
"""Calculo_material.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gPhw0Svpn27Jcvvu1a4Jd1YGw43A3Xhu
"""

from pandas._libs.tslibs.dtypes import periods_per_second
######Calculo de materiales#######
######Bienvenido##########

import pandas as pd
import numpy as np
import seaborn as sns


print("Calculo de materiales SFV para GIT")

flag = True
while flag:
  print("1) El arreglo de los paneles es lineal:")
  print("2) El arreglo es Cuadrado: ")
  print("3) Salir")

  opcion=(input("Ingrese una de las dos opciones:"))
  if opcion == '1':
   print("El arreglo es lineal")
   colum=int(input("Introduce el numero de paneles en forma lineal:"))
   ##Calculo de clemas media 1
   clemas_medias = (colum-1)*2
   print("El numero de clemas medias es:",clemas_medias)
    ###Calculo de clemas finales
   clema_final= 4
   print("El numero de clemas finales es:",clema_final)
   ### Calculo de climbers
   climb=(colum *2)
   print("El numero de climbers:",climb)
   ###Calculo de titl up
   titl_up1= colum
   print("Numero de titl up:",titl_up1)

   ##Calculo L-Foot
   l_foot=colum*2
   print("Elnumero de L foot es:",l_foot)


   ##Calculo de perfiles
   perfil1= 4.2
   perfil2= 4.60
   perfil3= 4.80
   med_ancho=float(input("Ingrese el ancho del panel:"))
   perfil_panel=(med_ancho*colum)+(clemas_medias*0.02)+0.20
   print("El largo del perfil es:",perfil_panel)
   #print("Los perfiles comerciales a continuación son los siguientes:",'opcion 1:',perfil1, ',','opcion2:',perfil2, ',','opcion3:',perfil3)
   print("/////////PERFILES////////////")
   print("////1) Perfil 1: 4.2 mts ////")
   print("////2) Perfil 2: 4.6 mts ////")
   print("////3) Perfil 3: 4.8 mts ////")
   print("////4) Salir //////////////")
   flag_aux = True
   while flag_aux:
    opcion_perfil= input("Ingrese la opción que necesites:")
    if opcion_perfil == '1':
      numero_perfil=(perfil_panel/perfil1)*2+((titl_up1*1.6)/perfil1)
      print("El numero de perfil es:",numero_perfil)
    elif opcion_perfil == '2':
      numero_perfil2=(perfil_panel/perfil2)*2+((titl_up1*1.6)/perfil2)
      print("El numero de perfil es:",numero_perfil2)
    elif opcion_perfil == '3':
      numero_perfil3=(perfil_panel/perfil2)*2+((titl_up1*1.6)/perfil3)
      print("El numero de perfil es:",numero_perfil3)
    elif opcion_perfil == '4':
      print("REGRESANDO A MENÚ PRINCIPAL ...")
      flag_aux = False


  elif opcion == '2':
   print("El arreglo es cuadrado")
   filas=int(input("Introduce el numero de filas de paneles:"))
   columnas=int(input("Introduce el numero de columnas de paneles:"))
   ##matriz=[]


   #for i in range(filas):
    #matriz.append([])
   #for j in range(columnas):
    #matriz.append([])
    #valor=float(input("Filas:{}".format (i+1 )))
    #valor1=float(input("Columnas:{}".format(j+1)))
    #matriz[i].append(valor)
   print("Numero de columnas:",filas)
   print("Numero de filas:",columnas)
   paneles=filas*columnas
   print("El numero de paneles es:",paneles)


   ##Calculo de clemas medias

   clem_medias=(columnas-1)*(filas*2)
   print("El numero de clemas medias es:",clem_medias)

    ###Calculo de clemas finales

   clem_final= filas*4
   print("El numero de clemas finales es:",clem_final)

   ### Calculo de climbers

   climber=columnas*(filas*2)
   print("El numero de climbers:",climber)

   ###Calculo de titl up

   titl_up= climber
   print("Numero de titl ups:",titl_up)


   ##Calculo de perfiles
    ##Calculo de perfiles
   perfil1= 4.2
   perfil2= 4.60
   perfil3= 4.80
   med_ancho=float(input("Ingrese el ancho del panel:"))
   perfil_panel=(med_ancho*colum)+(clemas_medias*0.02)+0.20
   print("El largo del perfil es:",perfil_panel)
   #print("Los perfiles comerciales a continuación son los siguientes:",'opcion 1:',perfil1, ',','opcion2:',perfil2, ',','opcion3:',perfil3)
   print("/////////PERFILES////////////")
   print("////1) Perfil 1: 4.2 mts ////")
   print("////2) Perfil 2: 4.6 mts ////")
   print("////3) Perfil 3: 4.8 mts ////")
   print("////4) Salir //////////////")
   flag_aux = True
   while flag_aux:
    opcion_perfil= input("Ingrese la opción que necesites:")
    if opcion_perfil == '1':
      numero_perfil=(perfil_panel/perfil1)*2+((titl_up1*1.6)/perfil1)
      print("El numero de perfil es:",numero_perfil)
    elif opcion_perfil == '2':
      numero_perfil2=(perfil_panel/perfil2)*2+((titl_up1*1.6)/perfil2)
      print("El numero de perfil es:",numero_perfil2)
    elif opcion_perfil == '3':
      numero_perfil3=(perfil_panel/perfil2)*2+((titl_up1*1.6)/perfil3)
      print("El numero de perfil es:",numero_perfil3)
    elif opcion_perfil == '4':
      print("REGRESANDO A MENÚ PRINCIPAL ...")
      flag_aux = False




  elif opcion == '3':
    print("Saliendo... \00/ GOODBYE ...")
    flag = False

med_ancho=float(input("Ingrese el ancho del panel:"))
   perfil_panel=(med_ancho*colum)+(clemas_medias*0.02)+0.20
   print("El largo del perfil es:",perfil_panel)
   print("Los perfiles comerciales a continuación son los siguientes:",perfil1,perfil2,perfil3)
   per= True
   opcion_perfil=(input("Ingrese el perfil que necesite"))
   while per:
    if opcion_perfil == '1':
      numero_perfil= opcion

2#calculo de protecciones
#df=pd.read_csv("/content/drive/MyDrive/CYBER_202211.csv")
#df.head()
import math
print("Calculo de protecciones")
flag=True
potencia =float(input("Ingrese la potencia del inversor:"))

while flag:
  print("El inversor es monofasico")
  print("El inversor es bifasico")
  print("El inversor es trifasico")
  opcion1=(input("Ingrese una de las siguientes tres opciones"))
  if opcion1 == '1':
   flag= False
   voltaje=float(input("Ingresa el voltaje de salida del inversor:"))
   amp=(potencia/voltaje)*1.25
   print("La protección en AC del inversor es:",amp)

  elif opcion1 == '2':
   flag = False
   voltaje2=float(input("Ingresa el voltaje de salida de voltaje"))
   amp2=(potencia/voltaje2)*1.25
   print("La protección en AC del inversor es:",amp2)
  elif opcion1 == '3':
   flag = False
   voltaje3= float(input("Ingrese el voltaje de salida del inversor:"))
   angulo=(math.sqrt(3))
   amp3=((potencia/(voltaje3*angulo))*(1.25))
   print("La protección en AC del inversor es de:",amp3,'A')

3   import math

   an= (math.sqrt(3))
   print("angulo",an)

#Suma de filas
from google.colab import drive
drive.mount("/content/drive/")

from google.colab import drive
drive.mount('/content/drive')

arreglo_panel={'A':[1,1,1],
               'B':[1,1,1],
               'C':[1,1,1]}
df= pd.DataFrame(arreglo_panel)
df

##Calculo de material eléctrico

##Tomar en cuenta 30 metros de cableado y tubería
##El inversor se debe decidir si queda arriba o abajo
cable_solar=30
print("La cantidad de cable es de:",cable_solar)





